### ISSUE TITLE
Plugin throws exception when timeouts are 0

### ISSUE THREAD

**Issue by malice00** [jenkinsci/dependency-track-plugin#251]
## Describe the bug
We recently updated to v5.0.0 of the plugin and noticed our builds were failing. After some testing we found that our configuration for the timeouts (which was set to 0 after some networking issues) were not accepted anymore. Seeing how the help text does still mention that it can be set to 0, we feel either the Exception should be fixed or the help should be changed accordingly.

Exception:
```
java.lang.IllegalArgumentException: Invalid duration: PT0S
  	at java.net.http/jdk.internal.net.http.HttpClientBuilderImpl.connectTimeout(HttpClientBuilderImpl.java:64)
  	at java.net.http/jdk.internal.net.http.HttpClientBuilderImpl.connectTimeout(HttpClientBuilderImpl.java:39)
  	at org.jenkinsci.plugins.DependencyTrack.ApiClient.lambda$new$0(ApiClient.java:101)
  	at org.jenkinsci.plugins.DependencyTrack.ApiClient.<init>(ApiClient.java:109)
  	at org.jenkinsci.plugins.DependencyTrack.ApiClient.<init>(ApiClient.java:101)
  	at org.jenkinsci.plugins.DependencyTrack.DependencyTrackPublisher.perform(DependencyTrackPublisher.java:289)
  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

## Environment

 - Plugin Version: 5.0.0
 - Jenkins Version: 2.452.2
 - Java Version for Jenkins: 17.0.8.1 / 17.0.11
 - Type of Jenkins Job: all
 - Dependency-Track Version: 4.11.4
 
## To Reproduce
1. Go to 'Manage Jenkins' / 'Sytem'
2. Scroll to 'Dependency-Track'
3. Click on 'Advanced'
4. Set 'Connection Timeout' and/or 'Response Timeout' to '0'
5. Save
6. Start a Job with Plugin configured
7. See error

## Expected behavior
No exception should occur.

**Comment by sephiroth-j** [comment]
You are definitely not using the official version v5.0.0. The plugin does not use the JDK HttpClient. It uses OkHTTP since PR #214.
